development:
  adapter: async
  allowed_request_origins:
    - http://localhost:3000
    - https://6c21-104-35-67-202.ngrok-free.app/new

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: gps_ambulance_notification_production
